(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-23',
          componentName:'@widget/SUBSCRIBE/bs-subscribe2-subscribe-form',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:"@widget/SUBSCRIBE/bs-subscribe2-subscribe-form"
        });
      })({"upgradeable":false,"preset":"subscribe2","id":"251f76ab-3c3f-4f31-9f21-40ad40e148f6","isInternalPage":false,"env":"production","websiteId":"17e7daf7-b8bb-4636-8628-2cbc4bb6e464","accountId":"8567c77d-2b65-11eb-81f7-3417ebe72595","hasNonCommercePlan":false,"couponToggleHidden":false,"sectionTitle":"Join Our Mailing List","staticContent":{"defaultButtonLabel":"Sign Up","emailPlaceholderText":"Email Address","verificationText":"To let us know it's really you and that you'd like to receive emails from us, please click the link in the confirmation email we just sent you. You can unsubscribe from these emails at any time.","emailErrorMessage":"Please enter a valid email address."},"confirmationMessage":"Excellent! We're excited to send you our next update.","couponConfirmationMessage":"Thanks so much for signing up!","description":"Be the first to hear about upcoming sales, hot trends, and new arrivals.","couponDescription":"Get 10% off your first purchase when you sign up for our newsletter!","inputPlaceholder":"Email","subscribeButtonLabel":"Sign up","couponToggle":false,"widgetId":"251f76ab-3c3f-4f31-9f21-40ad40e148f6","section":"default","category":"neutral","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"251f76ab-3c3f-4f31-9f21-40ad40e148f6","widgetType":"SUBSCRIBE","widgetPreset":"subscribe2","order":1,"section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Group","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});