(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-5',
          componentName:'@widget/LAYOUT/bs-CartIcon-Component',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:"@widget/LAYOUT/bs-CartIcon-Component"
        });
      })({"isShopPage":false,"appointmentsPageId":null,"shopPageId":"9254a694-d5f4-4fb8-a0b3-c1f692f40118","shopRoute":"\u002Fshop","accountId":"8567c77d-2b65-11eb-81f7-3417ebe72595","websiteId":"17e7daf7-b8bb-4636-8628-2cbc4bb6e464","olsStatus":"PROVISION_SUCCESS","olsAccountStatus":"ACTIVE","env":"production","rootDomain":"godaddy.com","domainName":"shop01bd.com","pageRoute":"\u002F","isReseller":false,"staticContent":{"hamburgerIcon":"Hamburger Site Navigation Icon","YouTube":"YouTube Social Link","cartProducts":"Products","Facebook":"Facebook Social Link","carouselAddImageHelper":"Click Here to Add Images to Slideshow!","membershipSectionTitle":"Account","membershipSignedInStatus":"Signed in as:","Xing":"Xing Social Link","membershipSignedOutStatus":"Currently not signed in","Houzz":"Houzz Social Link","morePages":"More","membershipBookings":"Bookings","Yelp":"Yelp Social Link","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","translateBarHelper":"Translate: ","promoBannerLink":"Promotion Banner Link","membershipAccount":"My Account","membershipSignIn":"Sign In","navigationDropdownToggle":"Website navigation dropdown menu","cartIcon":"Shopping Cart Icon","Pinterest":"Pinterest Social Link","membershipDropdownToggle":"Website member dropdown menu","membershipCreateAccount":"Create Account","membershipOrders":"Orders","membershipSignOut":"Sign out","membershipSignOutCaps":"SIGN OUT","search_placeholder":"Search Products","LinkedIn":"LinkedIn Social Link","cartServices":"Services"},"widgetId":"e6c237ce-01e0-43f3-9642-30dcc662446d","section":"default","category":"accent","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"e6c237ce-01e0-43f3-9642-30dcc662446d","widgetType":"HEADER","widgetPreset":"header9","section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"UtilitiesMenu","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});