(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-11',
          componentName:'@widget/LAYOUT/bs-NavOverflow-Component',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:"@widget/LAYOUT/bs-NavOverflow-Component"
        });
      })({"style":{"marginHorizontal":"-6px","marginVertical":"-6px","paddingHorizontal":"6px","paddingVertical":"6px"},"activeStyle":{"marginHorizontal":"-6px","marginVertical":"-6px","paddingHorizontal":"6px","paddingVertical":"6px"},"label":"More","parentId":"n-36873715-navId","toggleId":"3716-moreId","navBarId":"navBarId-3713","logoImageId":"logo-3712","navigation":[{"isFlyoutMenu":false,"active":true,"pageId":"7e6e6dde-fb70-4e79-9c6d-fbfe80683d64","name":"Home","href":"\u002F","target":"","visible":true,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":false},{"isFlyoutMenu":false,"active":false,"pageId":"9254a694-d5f4-4fb8-a0b3-c1f692f40118","name":"Shop","href":"\u002Fshop","target":"","visible":true,"requiresAuth":false,"tags":["SHOP"],"rel":"","type":"page","showInFooter":false}],"staticContent":{"hamburgerIcon":"Hamburger Site Navigation Icon","YouTube":"YouTube Social Link","cartProducts":"Products","Facebook":"Facebook Social Link","carouselAddImageHelper":"Click Here to Add Images to Slideshow!","membershipSectionTitle":"Account","membershipSignedInStatus":"Signed in as:","Xing":"Xing Social Link","membershipSignedOutStatus":"Currently not signed in","Houzz":"Houzz Social Link","morePages":"More","membershipBookings":"Bookings","Yelp":"Yelp Social Link","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","translateBarHelper":"Translate: ","promoBannerLink":"Promotion Banner Link","membershipAccount":"My Account","membershipSignIn":"Sign In","navigationDropdownToggle":"Website navigation dropdown menu","cartIcon":"Shopping Cart Icon","Pinterest":"Pinterest Social Link","membershipDropdownToggle":"Website member dropdown menu","membershipCreateAccount":"Create Account","membershipOrders":"Orders","membershipSignOut":"Sign out","membershipSignOutCaps":"SIGN OUT","search_placeholder":"Search Products","LinkedIn":"LinkedIn Social Link","cartServices":"Services"},"widgetId":"e6c237ce-01e0-43f3-9642-30dcc662446d","section":"default","category":"accent","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"e6c237ce-01e0-43f3-9642-30dcc662446d","widgetType":"HEADER","widgetPreset":"header9","section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Nav","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});